### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by craigyu** [ronram5126/steamworkshopdownloader#1]
I get this error when I run npm start. 
The urls examples look like file url not collection url, I tried both and none worked. :(

```> batchdownload@1.0.0 start /Users/craigyu/Downloads/steamWorkshopCrawler/steamworkshopdownloader-master
> node index.js

/Users/craigyu/Downloads/steamWorkshopCrawler/steamworkshopdownloader-master/node_modules/jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/craigyu/Downloads/steamWorkshopCrawler/steamworkshopdownloader-master/node_modules/jsdom/lib/jsdom/living/helpers/form-controls.js:18:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! batchdownload@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the batchdownload@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by ronram5126** [comment]
Hi Craigyu, sorry for delay. I have written this program very specifically. Could you please provide me the link to the workshop collection, I will test it and let you know.

**Comment by craigyu** [comment]
Hi, I already downloaded the files i need. 

Here is the list of urls i used

`https://steamcommunity.com/sharedfiles/filedetails/?id=911613539
https://steamcommunity.com/sharedfiles/filedetails/?id=531136613
https://steamcommunity.com/sharedfiles/filedetails/?id=947425570
https://steamcommunity.com/sharedfiles/filedetails/?id=680500415
https://steamcommunity.com/sharedfiles/filedetails/?id=691602861
https://steamcommunity.com/sharedfiles/filedetails/?id=429618056
https://steamcommunity.com/sharedfiles/filedetails/?id=427881811
https://steamcommunity.com/sharedfiles/filedetails/?id=678159892
https://steamcommunity.com/sharedfiles/filedetails/?id=526405282
https://steamcommunity.com/sharedfiles/filedetails/?id=1128919057
https://steamcommunity.com/sharedfiles/filedetails/?id=1812686836
https://steamcommunity.com/sharedfiles/filedetails/?id=1817611557
https://steamcommunity.com/sharedfiles/filedetails/?id=1832545585
https://steamcommunity.com/sharedfiles/filedetails/?id=1837236476
https://steamcommunity.com/sharedfiles/filedetails/?id=1860794227
https://steamcommunity.com/sharedfiles/filedetails/?id=1859290535
https://steamcommunity.com/sharedfiles/filedetails/?id=1859284188
https://steamcommunity.com/sharedfiles/filedetails/?id=1910177240
https://steamcommunity.com/sharedfiles/filedetails/?id=1883853907
https://steamcommunity.com/sharedfiles/filedetails/?id=1883855665
https://steamcommunity.com/sharedfiles/filedetails/?id=1897405591
https://steamcommunity.com/sharedfiles/filedetails/?id=1897406756
https://steamcommunity.com/sharedfiles/filedetails/?id=1886334945
https://steamcommunity.com/sharedfiles/filedetails/?id=1892983429
https://steamcommunity.com/sharedfiles/filedetails/?id=1890003393
https://steamcommunity.com/sharedfiles/filedetails/?id=1911328552
https://steamcommunity.com/sharedfiles/filedetails/?id=1225368249
https://steamcommunity.com/sharedfiles/filedetails/?id=739596970
https://steamcommunity.com/sharedfiles/filedetails/?id=612529562
https://steamcommunity.com/sharedfiles/filedetails/?id=1819666472
https://steamcommunity.com/sharedfiles/filedetails/?id=1937517089
https://steamcommunity.com/sharedfiles/filedetails/?id=1938795804
https://steamcommunity.com/sharedfiles/filedetails/?id=1945995597
https://steamcommunity.com/sharedfiles/filedetails/?id=1949792902
https://steamcommunity.com/sharedfiles/filedetails/?id=1964804537
https://steamcommunity.com/sharedfiles/filedetails/?id=1969532380
`


I wanted to download everything in this collection `https://steamcommunity.com/workshop/filedetails/?id=1817583362`
but i saw the url format is not the same as the ones in your example

It's NBD, just thought you might wanna know

**Comment by ronram5126** [comment]
hi craigyu,
I have fixed it to be able to download collection just add the url of colelction (not the url of the packages in the collection) in the urls.txt and try it. Sorry for delay mate, I was caught up trying to fix my pc.

Cheer man, be safe.
Ronit

**Comment by craigyu** [comment]
nice work dude, i saw your post on reddit, thought it's designed for downloading collection, maybe I read it wrong 😅
and stay safe yourself too, cheers
