### ISSUE TITLE
1 vulnerability + No download

### ISSUE THREAD

**Issue by JeromeHumbert** [ronram5126/steamworkshopdownloader#3]
Hi,

First of all thanks for this piece of work ! 

I'm encountering some difficulties to download mods from the workshop for Tabletop Simulator.

Here is all I made : 

> C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master>npm install
npm WARN batchdownload@1.0.0 No repository field.
added 103 packages from 138 contributors and audited 143 packages in 2.33s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master>npm audit fix
npm WARN batchdownload@1.0.0 No repository field.
up to date in 0.305s
fixed 0 of 1 vulnerability in 143 scanned packages
  1 vulnerability required manual review and could not be updated

> C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master>npm install
npm WARN batchdownload@1.0.0 No repository field.
added 103 packages from 138 contributors and audited 143 packages in 1.448s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master>npm start

> batchdownload@1.0.0 start C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master
> node index.js

> downloading The Settlers of Catan + Expansions (Scripted)

> C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master>npm start

> batchdownload@1.0.0 start C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master
> node index.js

> downloading The Settlers of Catan + Expansions (Scripted)

> C:\Users\Jerome\Desktop\steamworkshopdownloader-master\steamworkshopdownloader-master>npm audit

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  > Low             Prototype Pollution

  > Package         minimist

  > Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  > Dependency of   download-file

  > Path            download-file > mkdirp > minimist

  > More info       https://npmjs.com/advisories/1179

> found 1 low severity vulnerability in 143 scanned packages
  1 vulnerability requires manual review. See the full report for details.

I don't have a Download folder after that and can't find where it would be if it worked.

Do you know what could cause this ? 

The mod I'm trying to get is this one : https://steamcommunity.com/sharedfiles/filedetails/?id=694025908

Thanks in advance

Jerome

**Comment by ronram5126** [comment]
Hi Jerome,
Sorry for the inconvenience, but it only downloads collections in the steam workshop. There are other solutions for single packages. one which the program itself uses is [Steam Workshop Download](http://steamworkshop.download/download/view/694025908).

The vulnerability is low severity from the dependencies, I couldn't really do anything about it, as it has to be updated from the source itself. Anyway man, appreciate your input, Stay Safe.

Cheers,
Ronit

**Comment by JeromeHumbert** [comment]
Hi,

Thanks for your answer =) I'll try that. 

Stay safe as well !

Best regards

Jérôme
