### ISSUE TITLE
Downloads old version?

### ISSUE THREAD

**Issue by xavieerx** [ronram5126/steamworkshopdownloader#7]
I'm trying to download a mod collection for Rimworld and most mods are outdated when the mods themselves are updated.
I think some files aren't downloaded but i'm not sure.
Any help?

**Comment by xavieerx** [comment]
Turns out it's the site itself, closing.

**Comment by xavieerx** [comment]
Anyone know if it's the site or not?

**Comment by ronram5126** [comment]
Sorry for late reply, I have been busy. Send me the link for the site and I will test it...

**Comment by ronram5126** [comment]
Hi, I have uploaded a new update to the code, try redownloading it and running again.

**Comment by ronram5126** [comment]
Closing the issue due to no reply..
