### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by UsernameDjM8** [ronram5126/steamworkshopdownloader#8]
I got this error while i was trying to download a rimworld collection.
I followed all the steps writen in the readme.

https://imgur.com/a/mFzEMQ9

**Comment by ronram5126** [comment]
Send me what you are putting in the file to download I will test it.

Edit: If you could make sure that the links are to the collection, not the workshop itself. And that they are put in like in the example in url.txt file. Don't forget to delete the example URLs.

**Comment by UsernameDjM8** [comment]
well the links are to a workshop collections, and I put them in the urls.txt like in the example 

https://steamcommunity.com/sharedfiles/filedetails/?id=2106717330
https://steamcommunity.com/sharedfiles/filedetails/?id=2034377192

![links](https://user-images.githubusercontent.com/66163920/83345985-6ad7d780-a321-11ea-9888-0f819eb968a6.PNG)

**Comment by ronram5126** [comment]
I think it was something to do with steam. I have updated the code. try redownloading or pulling it, and run the command it should be working, it is downloading for me.

**Comment by UsernameDjM8** [comment]
It finally works. Thanks! I was searching for a tool like this one for a long time.
